server:
  port: 9006
  compression:
    enabled: true

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
#zuul:
#  routes:
#    bd:
#      path: /bd/**
#      url: http://www.baidu.com
#

zuul:
  routes:
    api:
        path: /**
        serviceId: eureka-client
