server:
  port: 9003

spring:
  application:
    name: feign-consumer-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
#  instance:
#    preferIpAddress: true

feign:
  hystrix:
    enabled: true